<?php

namespace WordWarsBundle\Repository;

/**
 * WordWarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordWarRepository extends \Doctrine\ORM\EntityRepository
{
}
