<?php

namespace UserBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  public function findRangedUsers($page = 0)
  {
    $results = $this
      ->createQueryBuilder('u')
      ->orderBy('u.username', 'ASC')
      ->setFirstResult($page)
      ->setMaxResults(100)
      ->getQuery()
      ->getResult();

    return $results;
  }
}
