<?php

namespace UserBundle\Repository;

/**
 * UserPreferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPreferencesRepository extends \Doctrine\ORM\EntityRepository
{
}
