<?php

namespace MyWordsBundle\Repository;

/**
 * DailyWordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyWordsRepository extends \Doctrine\ORM\EntityRepository
{
  public function findTodaysWords($user) {
    $date = new \Datetime(date('Y-m-d') . ' 00:00:00');

    $em = $this->createQueryBuilder('w');
    $em
      ->where('w.date >= :date')
      ->setParameter('date', $date);
    $em
      ->andWhere('w.user = :user')
      ->setParameter('user', $user);

    return $em->getQuery()->getOneOrNullResult();
  }
}
