<?php

namespace MyStatsBundle\Repository;

/**
 * MyDailyNanosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyNanosRepository extends \Doctrine\ORM\EntityRepository
{
  public function findThisMonthNano($user) {
    $starting_date = new \Datetime(date('Y-m') . '-01 00:00:00');
    $ending_date = new \Datetime(date('Y-m') . '-31 00:00:00');

    $em = $this->createQueryBuilder('w');
    $em
      ->where('w.date >= :starting_date')
      ->setParameter('starting_date', $starting_date);
    $em
      ->andWhere('w.date <= :ending_date')
      ->setParameter('ending_date', $ending_date);
    $em
      ->andWhere('w.user = :user')
      ->setParameter('user', $user);

    return $em->getQuery()->getOneOrNullResult();
  }
}
